name: First GitHub Actions Demo
on: 
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: actions/setup-node@v2
      uses: actions/setup-node@v2   
      with:
        node-version: '12'
    # 配置依赖缓存
    - name: yarn cache
      id: yarn-cahce-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      id: yarn-cache
      with: 
        path: ${{ steps.yarn-cahce-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: | 
          ${{ runner.os }}-yarn-
    # - run: yarn config set registry https://registry.npmmirror.com -g
    # - run: yarn config set sass_binary_site http://cdn.npmmirror.com/dist/node-sass -g
    - run: yarn install && yarn build
    # - run: npm config set registry https://registry.npmmirror.com
    # - run: npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
    # - run: npm install && npm run build
    # 新增 deploy
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages # 部署的分支名 有一定要独立一个分支，第一次设置为master 好家伙构建完成后，直接把我的项目文件清除了，只剩下打包的文件了。
        folder: build   # build后文件目录